services:
  db:
    image: mysql:8.0
    container_name: agendasena-db
    environment:
      MYSQL_ROOT_PASSWORD: MySQLdejulian1472.
      MYSQL_DATABASE: agendasena
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
